### ISSUE TITLE
Spanish (Latin America)

### ISSUE THREAD

**Issue by florianreinhart** [umpirsky/country-list#101]
There is a special language code for Spanish in Latin America: `es_419`.

http://www.unicode.org/cldr/charts/24/summary/es_419.html

Could you add support for this?

**Comment by umpirsky** [comment]
Thanks, but this data is coming form [ICU database](http://site.icu-project.org/), so that's where you should report issues. This just converts it to other formats.

**Comment by florianreinhart** [comment]
es_419 is Part of CLDR and should therefore also be available via ICU, see https://github.com/unicode-org/cldr/blob/release-36/common/main/es_419.xml

**Comment by Trainmaster** [comment]
@florianreinhart `es_419` was added in https://github.com/umpirsky/country-list/commit/0007d7ce1736f15ed691d1d35c7c32801a769753 and will be available in the next release.
