### ISSUE TITLE
Missing "BV" country code.

### ISSUE THREAD

**Issue by JamaisMagic** [umpirsky/country-list#103]
I checked the csv files of en, zh-hans-cn and pt-br languages, and could not find the area "BV" which is called "Bouvet Island" in English. The iso-3166-1 is listed here.

https://en.wikipedia.org/wiki/ISO_3166-1

https://en.wikipedia.org/wiki/Bouvet_Island

**Comment by umpirsky** [comment]
Thanks, but this data is coming form [ICU database](http://site.icu-project.org/), so that's where you should report issues. This just converts it to other formats.
