### ISSUE TITLE
Pseudo-Bidi & Pseudo-Accents entries

### ISSUE THREAD

**Issue by abePdIta** [umpirsky/country-list#112]
Hi!
What's the purpose of Pseudo-Bidi & Pseudo-Accents entries? I can't find information about this.
Should we filter them before showing list to user?
Thank you

**Comment by umpirsky** [comment]
Thanks, but this data is coming form [ICU database](http://site.icu-project.org/), so that's where you should report issues. This just converts it to other formats.
