### ISSUE TITLE
Kosovo - country code XK is missing

### ISSUE THREAD

**Issue by olivernybroe** [umpirsky/country-list#113]
We recently ran into this issue that the country code XK is missing. 

First I thought it was something wrong, an XK wasn't a country code, however it seems like Kosovo uses that one.

**Comment by kslimani** [comment]
I think (but i may be wrong !) `XK` is a temporary assigned code, so it it not yet assigned in ISO-3166 Alpha-2. _(and why it is not yet included when rebuilding assets)_. Use of `XK` for Kosovo is "user assigned" (and therefore not official ?)

```
The European Commission and many other organisations (Deutsche Bundesbank, Switzerland) 
are using ‘XK‘ as a temporary country code for Kosovo till ISO officially assigns a code.
```
Source : https://geonames.wordpress.com/2010/03/08/xk-country-code-for-kosovo/

Also i could not find Kosovo code at https://www.iso.org/obp/ui/#search  iso online database.

And it seems that building script is using PHP Intl extension to generate the country list.

**Comment by olivernybroe** [comment]
Ah alright. Yeah found some of the same information.

But I guess if XK should be there, then it's an issue in PHP Intl instead 👍 

Thanks!
