### ISSUE TITLE
Add UK alias for United Kingdom in the country list.

### ISSUE THREAD

**Issue by Messhias** [umpirsky/country-list#115]
The United Kingdom in the most of countries around the is known as the UK as well.

But the UK it's a standard for the whole EU and some other countries in the Asia and middle-east (e.g. India, United Arab Emirates, and most countries was a UK colony in the history).

**Comment by kslimani** [comment]
I think that UK code is not included because this project use Alpha-2 codes from the [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1#Coding) encoding list of the countries. _(it is an official list)_

Also interesting, the UK code is part of [exceptionally reserved code list](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Exceptional_reservations). _(Reserved on request of the United Kingdom)_

**Comment by Messhias** [comment]
> I think that UK code is not included because this project use Alpha-2 codes from the [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1#Coding) encoding list of the countries. _(it is an official list)_
> 
> Also interesting, the UK code is part of [exceptionally reserved code list](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Exceptional_reservations). _(Reserved on request of the United Kingdom)_

Ok, but what I can do about the regional requests? There's a way to work around that?

Because our customers will not be sent as GB country code ( they'll not accept anyway even there's a rational reason behind it).

For now, I'm converting everything it's UK to GB into our base, but, the customer will complain for sure.

**Comment by kslimani** [comment]
I already handled something similar in the past. If i remember correctly, i used to store iso country code, but also an optional (not iso) region code. The optional region code logic was handled on our side.

If i had to work again on such issue, i think i would probably build a library on the top this project.

**Comment by Messhias** [comment]
> I already handled something similar in the past. If I remember correctly, I used to store iso country code, but also an optional (not iso) region code. The optional region code logic was handled on our side.
> 
> If I had to work again on such an issue, I think I would probably build a library on top of this project.

If build a solution it'll be great, I was thinking to create a pull request just to add "UK" as the United Kingdom in the JSON files for the build generate the SQL, but when I saw there's a lot of regions/languages I don't know it'll be a good idea since the only languages that I have fluency in English and Portuguese.

What are your thoughts about my suggestion?

**Comment by kslimani** [comment]
This project is about ISO 3166-1 country codes list and "UK" code is not officially included in this list. I don't think it is a good idead to add it _(but it is my own opinion)_.

> For now, I'm converting everything it's UK to GB into our base, but, the customer will complain for sure.

My first thought would be to store both, work internally with ISO, and (if customer complain) use/display non ISO for customer.

When "adapt" thing to third party is required, i tend to build/wrap something on the top of internal architecture.

**Comment by Messhias** [comment]
> This project is about ISO 3166-1 country codes list and the "UK" code is not officially included in this list. I don't think it is a good idea to add it _(but it is my own opinion)_.
> 
> > For now, I'm converting everything it's UK to GB into our base, but, the customer will complain for sure.
> 
> My first thought would be to store both, work internally with ISO, and (if the customer complains) use/display non ISO for the customer.
> 
> When "adapt" thing to a third party is required, I tend to build/wrap something on top of internal architecture.

In that case, I don't think this is will gonna harm your system, you can create a table called "non_iso_countries" with all non-ISO countries inside, and when we try to look at a country by iso code when the record is not found on a table the system search in another. 

I know talking about it's not too easy to do, but this could be a nice enhancement for the library.

**Comment by Messhias** [comment]
@umpirsky can you please give some attention to the raised issues in the repository?

**Comment by umpirsky** [comment]
The problem is that this data is coming form CLDR database, so that's where you should report this kind of issues. This just exports it to other formats.

**Comment by Messhias** [comment]
> Hi. The problem is that this data is coming form CLDR database, so that's where you should report this kind of issues. This just exports it to other formats.

In other words there's no "solution" right?

**Comment by umpirsky** [comment]
The solution is to contribute the change to CLDR, wait for them to release new version, and rebuild this list.
