### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by Messhias** [umpirsky/country-list#116]
Since my raised issue on #115 seems not going anywhere I decided by myself to contribute.

But the readme isn't very detailed to how the countries list is generated.

Can you please update the readme.md?

Thank you

**Comment by umpirsky** [comment]
Since the repository is just a cldr database dump in various formats, the only way to contribute is to checkout the repository and rebuild the list by running [build](https://github.com/umpirsky/country-list/blob/master/bin/build) script.

**Comment by Messhias** [comment]
> Hi, thanks for bringing attention to this.
> 
> Since the repository is just a cldr database dump in various formats, the only way to contribute is to checkout the repository and rebuild the list by running [build](https://github.com/umpirsky/country-list/blob/master/bin/build) script.
> 
> Cheers.

Hi,

But where? When I should change? Because I tried to update some SQL's and examples and build running top on another package.

So what's your suggestion?

Thank you,

**Comment by umpirsky** [comment]
This is the home page of CLDR project http://cldr.unicode.org/.
