### ISSUE TITLE
"Syrian Arab Republic" country incorrectly named as "Syria"

### ISSUE THREAD

**Issue by Hubbitus** [umpirsky/country-list#121]
Please look at [country.php](https://github.com/umpirsky/country-list/blob/master/data/en/country.php#L218):
```php
'SY' => 'Syria',
```
But according to the [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) that should be `Syrian Arab Republic`

**Comment by umpirsky** [comment]
Thanks, but this data is coming form [ICU database](http://site.icu-project.org/), so that's where you should report issues. This just converts it to other formats.
