### ISSUE TITLE
Make IC - Canary Islands - available in all languages

### ISSUE THREAD

**Issue by AlinChindea** [umpirsky/country-list#122]
At the moment, IC - Canary Islands, seems to be available only on certain locales, such as [data/ms_Latn](https://github.com/umpirsky/country-list/blob/6dddae6983c1bc4d314b513c5decb7c8c6c879dc/data/ms_Latn/country.csv) or any `ms_Latn_*` files. Can you add it to the other languages? It has its own [ISO 3166-1 code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Exceptional_reservations)

Appreciated 🙏🏼

**Comment by umpirsky** [comment]
Thanks, but this data is coming form [ICU database](http://site.icu-project.org/), so that's where you should report issues. This just converts it to other formats.
