### ISSUE TITLE
Add tools to convert to different cases (PascalCase, snake_case, camleCase, kebab-case, etc...)

### ISSUE THREAD

**Issue by Snailedlt** [umpirsky/country-list#126]
Would be nice if it was possible to convert all countries from title case (the current case) into different cases.
 Maybe a few python or javascript functions could do the trick?

**Comment by umpirsky** [comment]
Thanks, but I think it's easy to do in your project and out of the scope of this one.

**Comment by Snailedlt** [comment]
Fair enough :)
