### ISSUE TITLE
"Taiwan" should be corrected to “Taiwan, China” or "Taipei, China"

### ISSUE THREAD

**Issue by GeorgeChan** [umpirsky/country-list#127]
Taiwan not a country, only province of China.
Reference source：https://data.un.org/en/index.html

**Comment by umpirsky** [comment]
Thanks, but this data is coming form [ICU database](http://site.icu-project.org/), so that's where you should report issues. This just converts it to other formats.

**Comment by psyll** [comment]
Taiwan is a self-governing democratic country, which has its own government, economy, and borders, and is not a part of the People's Republic of China
