### ISSUE TITLE
Missing Kosovo

### ISSUE THREAD

**Issue by approached** [umpirsky/country-list#128]
Hi @ all 

Missing Kosovo
https://en.wikipedia.org/wiki/Kosovo

ISO 3166 code | XK

**Comment by umpirsky** [comment]
Kosovo is partially recognized and this data is coming form [ICU database](http://site.icu-project.org/), so that's where you should report issues. This just converts it to other formats.

**Comment by dootix-developer** [comment]
I'm not an expert, but I can find the "XK" country code for Kosovo inside the ICU 74.1 release. Should this package get an update?
Thanks in advance!

**Comment by jackocnr** [comment]
@umpirsky thanks for this excellent package! I'm also missing XK (Kosovo) and after reading the last comment I'm wondering if this should now be included? Thank you so much 💐

**Comment by umpirsky** [comment]
You are free to [build](https://github.com/umpirsky/country-list#build) a new version and submit PR.
