### ISSUE TITLE
Add XI for Northern Ireland after Brexit

### ISSUE THREAD

**Issue by BlackbitDevs** [umpirsky/country-list#129]
According to https://en.wikipedia.org/wiki/ISO_3166-1#User-assigned_codes_in_wide_use `XI` has to be used for VAT numbers of trades between Northern Ireland and other countries of EU. It has not been added officially to ISO 3166-1 but is mandatory to be used for tax matters.

**Comment by umpirsky** [comment]
Thanks, but this data is coming form [ICU database](http://site.icu-project.org/), so that's where you should report issues. This just converts it to other formats.
