### ISSUE TITLE
I suggest changing the source also to my repo where I keep the updated list from iso.org

### ISSUE THREAD

**Issue by detrin** [umpirsky/country-list#132]
I prepared a repo where you can use the CLI to fetch the newest ISO 3166 list or use the countries.json file. https://github.com/detrin/download-iso3166-list

**Comment by umpirsky** [comment]
Does it have i18n?

**Comment by detrin** [comment]
I am not sure what exactly is i18n in this context. Do you mean alpha2 codes? Then yes. An example
```
{
    "Alpha-2 code": "US",
    "Alpha-3 code": "USA",
    "English short name": "United States of America (the)",
    "French short name": "États-Unis d'Amérique (les)",
    "Numeric": "840"
  }
  ```
https://raw.githubusercontent.com/detrin/download-iso3166-list/main/countries.json
This is exactly taken from iso.org. If you would be interested I could alter the CLI so it fetches other details about countries.

**Comment by umpirsky** [comment]
Yeah, I was referring to country names in other languages. 

I'm not interested at the moment, but thanks for offering, if someone sees a value in this we might consider adding a new source in the future.

**Comment by detrin** [comment]
Okay, thanks for the response.
