### ISSUE TITLE
[Proposal] One file with each country it its own language

### ISSUE THREAD

**Issue by lsv** [umpirsky/country-list#33]
Fx.

If I had chosen russia, I would not be able to find my own country again.

So I would say it would be nice to have 1 file, with each country it is own language.

Fx
Germany = Deutschland
Mexico = Mexicanos
Denmark = Danmark
Russia = Российская

maybe put it in country/general/country.*

**Comment by igsm** [comment]
actually Russia is - Россия (not Российская)

**Comment by umpirsky** [comment]
@igsm What file?

**Comment by igsm** [comment]
Sorry I am not sure which file, I just made a remark on the snippet of Isv's comment...

**Comment by umpirsky** [comment]
Ping @lsv. :)

**Comment by lsv** [comment]
I cant remember which file I copy/pasted from, properly taken from multiple files.
