### ISSUE TITLE
Watch out USSR in the list! 

### ISSUE THREAD

**Issue by igsm** [umpirsky/country-list#41]
Union of Soviet Socialist Republics... you are kidding!

Thanks for snippet but after this (USSR) I will need to check each country if it is not a joke.

**Comment by umpirsky** [comment]
@igsm What file?

**Comment by igsm** [comment]
country-list/country/cldr/en/country.postgresql.sql

I usually come across with ~250 countries offered in the html select field. Your is 264.

I have uploaded mine. I pulled this list from the one commercial website. Can't guarantee 100% accuracy but looks fine from the fist glance.

https://github.com/igsm/postgresql-country-list

**Comment by umpirsky** [comment]
@igsm I can't find USSR in https://github.com/umpirsky/country-list/blob/master/country/cldr/en/country.postgresql.sql?

**Comment by igsm** [comment]
line 249 - Union of Soviet Socialist Republics

**Comment by igsm** [comment]
I also checked one doubtful case - 'Serbia and Montenegro' and of course it is in the list. Now there are two separate countries, which are also included but you should remove S&M :)

**Comment by umpirsky** [comment]
@igsm I am from Serbia, no worries. :)

It's CLDR providing this regions.

You can consider using ICU data instead https://github.com/umpirsky/country-list/blob/master/country/icu/en/country.postgresql.sql.

**Comment by igsm** [comment]
Alrightttttt..... hah

**Comment by umpirsky** [comment]
:+1:
