### ISSUE TITLE
SQL Server unicode literals

### ISSUE THREAD

**Issue by soheilpro** [umpirsky/country-list#42]
SQL Server literals require an N before the unicode text.

Wrong:
```
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'آروبا');
```

Correct:
```
INSERT INTO [country] ([id], [name]) VALUES ('AW', N'آروبا');
```

**Comment by umpirsky** [comment]
@soheilpro Thanks for reporting this, will take a look when I have time,

**Comment by umpirsky** [comment]
SQL server support is dropped in v2.0.
