### ISSUE TITLE
zh-CN vs zh_CN?

### ISSUE THREAD

**Issue by mendrinos** [umpirsky/country-list#45]
My locale for Chinese is: zh-CN and your folder name is: zh_CN.

Any ideas on which is the best way to address this?

What I am getting is:
Unable to load the country data file "/home/vagrant/development/engine/vendor/umpirsky/country-list/country/cldr/zh-CN/country.php"

**Comment by umpirsky** [comment]
Hi, thanks for reporting.

Where do you get this error? Can you provide a trace, or how to reproduce?

**Comment by mendrinos** [comment]
![screen shot 2015-10-06 at 9 24 12 am](https://cloud.githubusercontent.com/assets/1592441/10298031/415178c2-6c0c-11e5-85c8-980e69349710.png)

This is my locale definition, and googled it a bit and found that the dash '-' is better than the underscore '_'..

so the usage of the country list is for a drop down for country selections:

```
<select id="company_country_code" name="company_country_code">
    @foreach (Countries::getList(App::getLocale()) as $key => $country) // this is where it breaks
        <option value="{{{$key}}}"@if(GeoIP::getLocation()['isoCode'] == $key) selected="selected" @endif>{{{$country}}}</option>
    @endforeach
</select>
```

**Comment by umpirsky** [comment]
Well, this is just a convention.

You can also try ICU https://github.com/umpirsky/country-list/blob/master/country/icu/en/country.csv.
