### ISSUE TITLE
composer PHP requirements fails on PHP7

### ISSUE THREAD

**Issue by stadskle** [umpirsky/country-list#53]
In your composer file you are using ~5.4, which causes composer to fail when using PHP7. I assume there is not reason that the package should not be used on PHP7? If not I suggest to change to >=5.4

Error when running composer:

```umpirsky/country-list dev-master requires php ~5.4 -> your PHP version (7.0.2) does not satisfy that requirement```

**Comment by umpirsky** [comment]
Fixed in master, thanks @stadskle. :+1:

**Comment by MidnightDesign** [comment]
Would you mind tagging a new version so I don't have to change my dependencies to `dev-master`?

**Comment by umpirsky** [comment]
@MidnightDesign Tagged `2.0.2`. ;)

**Comment by MidnightDesign** [comment]
Awesome. Thanks!
