### ISSUE TITLE
PHP 7

### ISSUE THREAD

**Issue by antzhdanov** [umpirsky/country-list#57]
This should work perfectly with PHP 7, but it it's composer.json says 
`"php": "~5.4"`

What about updating this?

**Comment by umpirsky** [comment]
@antzhdanov Sure, thanks, it should be `"php": ">=5.4"`, would you like to submit PR?

**Comment by antzhdanov** [comment]
Sure, let me do it.

**Comment by umpirsky** [comment]
@antzhdanov Thanks! :+1:

**Comment by antzhdanov** [comment]
Sorry just figured out that I was referencing the old version 2.0.0 which indeed had "~5.4" in require section and this was already fixed here: https://github.com/umpirsky/country-list/issues/53.

**Comment by umpirsky** [comment]
LoL!
