### ISSUE TITLE
make it available for npm

### ISSUE THREAD

**Issue by bogomips** [umpirsky/country-list#58]
It is a great job, you should make it available for npm, a lot of people would apreciate and use it.

**Comment by umpirsky** [comment]
Thanks. I'm not sure how npm is suitable because of the repo size. However, npm does allow to reference git repo direcly, right? So you can still use it.

**Comment by n-sviridenko** [comment]
It's impossible without the `package.json`. Would you add it, please?

**Comment by umpirsky** [comment]
@n-sviridenko Did you read https://docs.npmjs.com/files/package.json#repository? I think it is.

**Comment by n-sviridenko** [comment]
@umpirsky as I know, it is possible to use git repositories, but it should contain `package.json` in the root folder.

**Comment by n-sviridenko** [comment]
https://github.com/umpirsky/country-list/pull/71
