### ISSUE TITLE
en list missing 'EU' country code

### ISSUE THREAD

**Issue by Stretch96** [umpirsky/country-list#64]
All lists under `data/en` are missing the 'EU' country code ('EU' => 'European Union')

It is in `data/en_MU` and a few others

**Comment by umpirsky** [comment]
I can't find it in https://github.com/umpirsky/country-list/blob/master/data/en_MU/country.csv.

If it is in some file, that's probably an issue, since EU is not a country.

**Comment by Dexus** [comment]
EU is no country... so close this...
