### ISSUE TITLE
Missing AN BV CS HM country code

### ISSUE THREAD

**Issue by o-Chamie-o** [umpirsky/country-list#70]
Hi,

Thanks for the great job. :)

The AN : 'Netherlands Antilles'
BV : 'Bouvet Island (Bouvetoya)'
CS :  'Serbia' https://en.wikipedia.org/wiki/ISO_3166-2:CS
HM : 'Heard Island and McDonald Islands'

Are missing.

**Comment by umpirsky** [comment]
Thanks, but this data is coming form ICU database, so that's where you should report issues. This just converts it to other formats.
