### ISSUE TITLE
CZech Republic wrong name in Italian

### ISSUE THREAD

**Issue by MEBlabs** [umpirsky/country-list#82]
Hi,
the name should be "Repubblica Ceca" instead of "Cèchia" that is the original name in "corso" language

**Comment by umpirsky** [comment]
Thanks, but this data is coming form ICU database, so that's where you should report issues. This just converts it to other formats.

**Comment by MEBlabs** [comment]
Could you link the ICU website?

**Comment by umpirsky** [comment]
http://site.icu-project.org/
