### ISSUE TITLE
A few corrections for German

### ISSUE THREAD

**Issue by StephanWagner** [umpirsky/country-list#88]
There are three incorrect countries I found in German de_DE:

Kongo-Brazzaville > Republik Kongo
Kongo-Kinshasa > Demokratische Republik Kongo
Botsuana > Botswana

Cheers,
Stephan

**Comment by umpirsky** [comment]
Thanks, but this data is coming form [ICU database](http://site.icu-project.org/), so that's where you should report issues. This just converts it to other formats.
