### ISSUE TITLE
Taiwan wrong name in all languages

### ISSUE THREAD

**Issue by hugojing** [umpirsky/country-list#89]
Taiwan's correct name in _ISO 3166-1, ISO_3166-2:CN, ISO 3166-2:TW is:

- **Taiwan, Province of China** in English
- **中国台湾省** in Chinese
- **Taïwan, Province de Chine** in French

You can see: https://en.wikipedia.org/wiki/ISO_3166-1#Naming_and_code_construction, thanks for your view.

**Comment by umpirsky** [comment]
Thanks, but this data is coming form [ICU database](http://site.icu-project.org/), so that's where you should report issues. This just converts it to other formats.
