### ISSUE TITLE
Missing "BV" and "HM" country codes

### ISSUE THREAD

**Issue by mrcage** [umpirsky/country-list#91]
The following country codes are missing:

- `HM` Heard Island and McDonald Islands (https://laendercode.net/en/2-letter-code/hm)
- `BV` Bouvet Island (https://laendercode.net/en/2-letter-code/bv)

**Comment by umpirsky** [comment]
Thanks, but this data is coming form [ICU database](http://site.icu-project.org/), so that's where you should report issues. This just converts it to other formats.
