### ISSUE TITLE
Why is 'United Nations' being shown in the results?

### ISSUE THREAD

**Issue by kruncher** [umpirsky/country-list#93]
This isn't even showing under the data on the master branch.

I installed with composer using `composer require umpirsky/country-list`.

**Comment by umpirsky** [comment]
Thanks, but this data is coming form [ICU database](http://site.icu-project.org/), so that's where you should report issues. This just converts it to other formats.

**Comment by kruncher** [comment]
Sorry but I think my question was misunderstood;

what I meant was...

Why is the data on your master branch not consistent with what is coming from composer? On master branch 'United Nations' is not included. Shouldn't master reflect what is currently being installed by composer?

**Comment by umpirsky** [comment]
[Released](https://github.com/umpirsky/country-list/releases) version 2.0.5, now it should reflect, thanks.
