### ISSUE TITLE
pseudolocales listed as countries in latest data version

### ISSUE THREAD

**Issue by Huulivoide** [umpirsky/country-list#94]
It seems that commit 05fda51cd97b3294e8175ffed06104c44b3c71d7 has introduced pseudolocales XA and XB as countries, which they are not, to the data set.

**Comment by kslimani** [comment]
@umpirsky i confirm the issue. The "XA" and "XB" should not be present. For example [here](https://github.com/umpirsky/country-list/blob/master/data/fr/country.php#L188) in french. _(but not  only in fr file)_.

**Comment by smonff** [comment]
I confirm this issue.
