### ISSUE TITLE
Missing country codes

### ISSUE THREAD

**Issue by lukasvitroleracc** [umpirsky/country-list#98]
Countries missing that I noticed:
'BV' => Bouvet Island (https://en.wikipedia.org/wiki/ISO_3166-2:BV)
'HM' =>  Heard Island and McDonald Islands (https://en.wikipedia.org/wiki/ISO_3166-2:HM)

**Comment by umpirsky** [comment]
Thanks, but this data is coming form [ICU database](http://site.icu-project.org/), so that's where you should report issues. This just converts it to other formats.

**Comment by lukasvitroleracc** [comment]
https://st.unicode.org/cldr-apps/v#/en/T_SAmerica/37583b3169581a0c
https://st.unicode.org/cldr-apps/v#/en/T_Oceania/136260adbfeb06fe

They exist there. What list do you mean?

**Comment by umpirsky** [comment]
Then we just need to udpate. :)
